# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56181b0fe85337c5addd2b1e43fabd3f97b9f5d4e0efd7e0cc1948bc7a6022d90535c607226d663438b1cc9c36ff5ae91534378f6ff3af88514fe3baf0c4ece5

test:
  secret_key_base: eb61b5b5c45b6fd5ff47bf5d152cbc8c4d53f0c0ac0ddb3c8761827828df5e2cda1409ec850645d607a4e451f7603611c1b968b4b95c535cfd00975477c69a37

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
